### ISSUE TITLE
Expanded GLM offering

### ISSUE THREAD

**Issue by Weekend-Warrior** [rexyai/rsparse#18]
From FTRL, I saw that Poisson regression is on your to-do list. As an alternative, I'd like to suggest that you consider an implementation of the Tweedie family which allows, through tuning parameters, the Gaussian, Poisson, Gamma and Inverse Gaussian families, as well as the gradients between.

**Comment by dselivanov** [comment]
Contributions/pull requests are very welcome. Not sure I will have time in near future to work on it.
