### ISSUE TITLE
EigenRec: Generalizing PureSVD for Effective and Efficient Top-N Recommendations

### ISSUE THREAD

**Issue by dselivanov** [rexyai/rsparse#29]
https://arxiv.org/pdf/1511.06033.pdf

**Comment by mscbuck** [comment]
I noticed that there was a commit that implements the ScaleNormalize in the dev version of rsparse? Is there any guide on how one would use it? I imagine I would simply provide a dense symmetric matrix of item-item similarity (whatever measures), and then would use the resulting scaled matrix out of ScaleNormalize, perform SVD, and multiply to match Eq (13) in the paper?

**Comment by dselivanov** [comment]
I've added support via scaling input matrix (which corresponds to `cosine` similarity matrix from the paper).

```r
# fit models
sn = ScaleNormalize$new(scale = 0.5, target = "columns")
x_train_normalized = sn$fit_transform(x_train)
psvd = PureSVD$new(rank = 8)
user_emb = psvd$fit_transform(x_train_normalized, n_iter = 10, convergence_tol = 0.01)

# predict
x_test_normalized = sn$transform(x_test)
preds = psvd$predict(x_test_normalized, k = 10)
```
